# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
pr:
  - master

pool:
  vmImage: 'ubuntu-16.04'

stages:
  - stage: check
    jobs:
      - job: code_style_check
        steps:
          - script: sudo apt-get install libxml2-utils
            displayName: 'Install xmllint dependency'
          - script: make
            displayName: 'Check code style'
  - stage: test
    jobs:
      - job: maven_test
        steps:
          - script: mvn test
            displayName: 'Maven test'

